# Generated by Django 5.2.3 on 2025-09-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='approved_by',
            new_name='approved_by_user',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='requested_by',
            new_name='requested_by_user',
        ),
    ]
