# Generated by Django 5.2.3 on 2025-09-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_rename_approved_by_purchaseorder_approved_by_user_and_more'),
        ('purchase_request', '0003_purchaserequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchase_request.purchaserequest'),
        ),
    ]
