# Generated by Django 5.2.3 on 2025-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorder_purchase_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='refuse_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
