# Generated by Django 5.2.3 on 2025-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorder_refuse_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
