# Generated by Django 5.2.3 on 2025-11-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_purchaseorder_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
