# Generated by Django 5.2.3 on 2025-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_alter_purchaseorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
