# Generated by Django 5.2.3 on 2025-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_purchaseorder_supplier_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(blank=True, choices=[('TND', 'TND'), ('USD', 'USD'), ('EUR', 'EUR')], default='TND', max_length=10, null=True),
        ),
    ]
