# Generated by Django 5.2.3 on 2025-12-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_remove_purchaseorder_status_purchaseorder_currency'),
        ('reject_reasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='rejected_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_reason', to='reject_reasons.rejectreason'),
        ),
    ]
