# Generated by Django 5.2.3 on 2025-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_purchaseorder_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='statuss',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
