# Generated by Django 5.2.3 on 2026-02-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('purchase_order', '0011_add_supplier_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_by_department', to='department.department'),
        ),
    ]
