# Generated by Django 4.2.28 on 2026-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0012_purchaseorder_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='statut_line',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('approved', 'Approved'), ('for_modification', 'For Modification')], default='for_modification', max_length=20),
        ),
    ]
