# Generated by Django 4.2.28 on 2026-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0013_purchaseorder_po_number_alter_purchaseorder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='statuss',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], default='pending', max_length=20),
        ),
    ]
