# Generated by Django 4.2.28 on 2026-04-08 08:44

from django.db import migrations


def migrate_json_to_lines(apps, schema_editor):
    """Migrer les données du JSONField vers les PurchaseOrderLine"""
    PurchaseOrder = apps.get_model('purchase_order', 'PurchaseOrder')
    PurchaseOrderLine = apps.get_model('purchase_order', 'PurchaseOrderLine')
    
    for po in PurchaseOrder.objects.all():
        if po.products and isinstance(po.products, list):
            for product_data in po.products:
                try:
                    # Créer une ligne pour chaque produit dans le JSON
                    line = PurchaseOrderLine(
                        purchase_order=po,
                        product_id=product_data.get('product_id'),
                        supplier_id=product_data.get('supplier_id'),
                        quantity=product_data.get('quantity', 1),
                        unit_price=product_data.get('unit_price', 0),
                        status='pending'  # Tous les produits existants sont en attente
                    )
                    line.save()
                except Exception as e:
                    print(f"Erreur lors de la migration de PO {po.id}: {e}")
                    continue


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0013_purchaseorderline'),
    ]

    operations = [
        migrations.RunPython(migrate_json_to_lines),
    ]
