# Generated by Django 5.2.3 on 2025-07-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='role.role'),
        ),
    ]
