# Generated by Django 5.2.3 on 2025-12-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_user_role_id'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dep_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department'),
        ),
    ]
