# Generated by Django 5.2.3 on 2026-03-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
    ]
