# Generated by Django 5.2.3 on 2025-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0002_alter_purchaserequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
