# Generated by Django 5.2.3 on 2025-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0003_purchaserequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
