# Generated by Django 5.2.3 on 2025-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0004_purchaserequest_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('transformed', 'Transformed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
