# Generated by Django 5.2.3 on 2026-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0005_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('transformed', 'Transformed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
