# Generated by Django 5.2.3 on 2025-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='matricule_fiscale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
