# Generated by Django 5.2.3 on 2025-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_cin_supplier_matricule_fiscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
