# Generated by Django 5.2.3 on 2026-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_contact_name_supplier_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code_fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
