# Generated by Django 5.2.3 on 2026-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_code_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
