# Generated by Django 5.2.3 on 2026-02-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplier_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('avg_order', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('by_subcategory', models.JSONField(blank=True, help_text='{"subcategory_id": {"name": str, "total": float, "orders": int}}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='supplier.supplier')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('supplier', 'date')},
            },
        ),
    ]
